title:            Jaakko Santala
tagline:          Software consulting
description:      You drink your milkshake

port: 3000
host: https://hypermurea.github.io/hypermurea.com/
safe: false

canonical: http://jekyll.gtat.me

# Owner/author information
owner:
  name:           Jaakko Santala
  avatar:         avatar.png
  bio:            "Dilettante"
  email:          jaakko@hypermurea.com
  github:         hypermurea
  # Plug in your disqus shortname!

tools:
  standards:      "HTML, SCSS, Jekyll"
  software:       "git"

# Open Graph customization
opengraph:
  locale:           en_US

# Links to include in top navigation
# For external links add external: true
links:
  - title: Consultancy
    url: /
  - title: Drabbles
    url: /drabbles
  - title: Linkedin
    url: https://fi.linkedin.com/in/jaakkosantala
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Finland/Helsinki
future:      true
highlighter: pygments
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

sass:
    style: :compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
